// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqDnavn3TA1j87JghiAJ9AnclZd8mkO4',
    appId: '1:627417788456:web:0f694c68673f1bb651051d',
    messagingSenderId: '627417788456',
    projectId: 'seanskayit',
    authDomain: 'seanskayit.firebaseapp.com',
    databaseURL: 'https://seanskayit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'seanskayit.appspot.com',
    measurementId: 'G-4QBF8E8EZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEYrLhqFQyg3vQNS-PpmlW1t1MR_fETOI',
    appId: '1:627417788456:android:7b2ecbbd37e6423f51051d',
    messagingSenderId: '627417788456',
    projectId: 'seanskayit',
    databaseURL: 'https://seanskayit-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'seanskayit.appspot.com',
  );
}
